spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.125.238.234:3306/itda?autoReconnect=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
  profiles:
    active: local

  redis:
    port: 6379
    host: 13.125.238.234
    password: itda


jwt:
  secret: yeon
  token-validity-in-seconds: 86400

oauth:
  naver:
    client_id: boxzCRuNeP0Gvv5BGhcM
    secret: VxBPfkIQ2t
  kakao:
    client_id: ee6e1a4937fbdd837c05bf548215a3ae
    secret: QLSuY5JZW7zxIu28Q64gBXLt0Gkon7RO
server:
  port: 8000

